services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - 5433:5432
    restart: always
    volumes:
      -db:/var/lib/postgresql/data
    env_file:
      - .env
  
  node:
    container_name: node
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - back-end/.env

volumes:
  -db: